#!/bin/bash

ERRORS=0

# bad things in javascript
JSCHANGES=`git diff --cached -G'console\.log' --name-only -- '*.js' '*.coffee'`
if [[ ! "${JSCHANGES}" == "" ]]
then
  echo
  echo "COMMIT REJECTED Found 'console.log' references."
  echo "look in: ${JSCHANGES}"
  ERRORS=1
fi

# bad things in specs
SPECCHANGES=`git diff --cached -G':focus|focus.*true' --name-only -- '*.rb'`
if [ ! "${SPECCHANGES}" == "" ]
then
  echo
  echo "COMMIT REJECTED Found \":focus\" or \"focus: true\". "
  echo "look in: ${SPECCHANGES}"
  ERRORS=1
fi

if [[ "$ERRORS" -ne "0" ]]
then
  echo
  echo "Please remove them before commiting."
  exit 1
fi

# make sure that ruby files don't get more complex
if command -v flog >/dev/null 2>&1
then
  for change in $(git diff --name-only origin/master | cat | grep '.rb')
  do 
    current=`cat ${change} | flog --19 -s | grep total | cut -d':' -f1 | sed -e "s/ //g"`
    remote=`git show origin/master:${change} 2>/dev/null | flog --19 -s | grep total | cut -d':' -f1 | sed -e "s/ //g"`
    if [ "${remote}" = "0.0" ]
    then 
      echo "skipping… file does not exist on remote"
    elif [[ "${remote}" < "${current}" ]]
    then
      echo "Please make sure that the file ${change}, which now has a complexity score of ${current}, isn't any higher than ${remote}"
      echo "... then try again."
      exit 1
    fi
  done
else
  echo "You must install the flog gem to enjoy the flog goodness!"
  echo "gem install flog"
fi

exit 0

